import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,step,snapshot,restore,normalizeInput,damagePlayer,collect,resolveTerminal,enterAssisted,chooseAssisted,closeRun} from '../public/games/aerial-shooter/core.js';
import {LEVEL,OPPORTUNITIES,MIDPOINT_SECONDS,BOSS_SECONDS} from '../public/games/aerial-shooter/level.js';
import {T} from '../public/games/aerial-shooter/tuning.js';
const run=(s,n,input={})=>{for(let i=0;i<n;i++)step(s,input);return s;};
const checkpoint=(at=BOSS_SECONDS)=>{const s=createRun();s.tick=s.levelTick=at*60-1;s.cursor=LEVEL.findIndex(e=>e.at>=at);step(s);return s;};
test('fixed step, normalized opposing/diagonal movement, clamps',()=>{assert.deepEqual(normalizeInput({left:1,right:1}),{x:0,y:0});assert.equal(Math.hypot(...Object.values(normalizeInput({up:1,left:1}))),1);const s=createRun();run(s,60,{right:true,up:true});assert.ok(Math.abs(Math.hypot(s.player.x-320,s.player.y-300 )-198)<1e-7);run(s,300,{right:true});assert.equal(s.player.x,632);assert.throws(()=>step(s,{},.1));});
test('save/restore resumes exact enemies, cooldowns, bullets and events',()=>{const s=run(createRun({seed:17}),1865,{left:true});const resumed=restore(s.config,snapshot(s));run(s,450,{right:true});run(resumed,450,{right:true});assert.deepEqual(snapshot(s),snapshot(resumed));});
test('all eight loadouts implement exact movement, hull and damage',()=>{for(let mask=0;mask<8;mask++){const loadout=['agility','armor','weapons'].filter((_,i)=>mask&(1<<i));const s=createRun({loadout});run(s,30,{right:1});assert.equal(s.maxHealth,mask&2?150:100);assert.ok(Math.abs(s.player.x-320-(mask&1?118.8:99))<1e-8);assert.equal(s.friendly[0].damage,mask&4?15:10);}});
test('ordinary and heavy damage honor one second protection',()=>{const s=createRun();s.player.protection=0;assert.equal(damagePlayer(s,10),true);assert.equal(s.health,90);assert.equal(damagePlayer(s,20),false);run(s,60);damagePlayer(s,20);assert.equal(s.health,70);});
test('three lives; midpoint rewinds progress not time; armor and spent supplies survive',()=>{const s=checkpoint(MIDPOINT_SECONDS);s.config.loadout=['armor'];s.maxHealth=s.health=150;collect(s,{kind:'spread',opportunity:'SPREAD-1'});run(s,30);s.health=0;const elapsed=s.tick;resolveTerminal(s);assert.equal(s.lives,2);assert.equal(s.tick,elapsed);assert.equal(s.levelTick,9000);assert.equal(s.health,150);assert.equal(s.bonus,null);assert.deepEqual(s.collected,['SPREAD-1']);s.health=0;resolveTerminal(s);s.health=0;resolveTerminal(s);assert.equal(s.outcome,'defeat');assert.equal(s.lives,0);});
test('boss checkpoint restores all components and clears threats',()=>{const s=checkpoint();assert.ok(s.boss);s.boss.guns=[0,1];s.boss.core=42;s.health=0;resolveTerminal(s);assert.deepEqual(s.boss.guns,[240,240]);assert.equal(s.boss.core,600);assert.equal(s.boss.phase,'entry');assert.deepEqual(s.hostile,[]);assert.equal(s.levelTick,13500);});
test('six stable supply opportunities, replacement, capped repair and replay suppression',()=>{assert.equal(OPPORTUNITIES.length,6);assert.equal(new Set(OPPORTUNITIES).size,6);const s=createRun();collect(s,{kind:'spread',opportunity:'SPREAD-1'});assert.equal(s.bonus.ticks,1200);collect(s,{kind:'wingman',opportunity:'WINGMAN-1'});assert.deepEqual(s.bonus,{kind:'wingman',ticks:1800});collect(s,{kind:'repair',opportunity:'REPAIR-1'});assert.equal(s.message,'Hull full');assert.equal(s.health,100);collect(s,{kind:'repair',opportunity:'REPAIR-1'});assert.equal(s.counters.pickups,3);});
test('terminal precedence: defeat, then boss kill, then active expiry; immutable',()=>{for(const [lives,hp,boss,outcome] of [[1,0,0,'defeat'],[2,0,0,'success'],[3,100,1,'escape_lesser'],[3,100,0,'success']]){const s=checkpoint();s.tick=18000;s.lives=lives;s.attempt=3-lives;s.counters.deaths=s.attempt;s.health=hp;s.boss.core=boss;resolveTerminal(s);assert.equal(s.outcome,outcome);const old=snapshot(s);step(s);closeRun(s,'window_closed');assert.deepEqual(snapshot(s),old);}});
test('assisted route freezes action clock, retries and cannot reopen terminal',()=>{const s=createRun();run(s,90);enterAssisted(s);run(s,90);assert.equal(s.tick,90);assert.equal(chooseAssisted(s,2),false);assert.equal(s.assistedStep,0);for(const answer of [0,1,0])assert.equal(chooseAssisted(s,answer),true);assert.equal(s.outcome,'assisted_completed');assert.equal(s.counters.guns,0);assert.equal(enterAssisted(s),false);});
test('malformed/revision-mismatched snapshots fail explicitly',()=>{const s=createRun();for(const edit of [v=>v.tick=-1,v=>v.config.game='old',v=>v.lives=9,v=>v.collected=['fake'],v=>v.player.x=NaN,v=>v.enemies=[{id:'fake',x:0,y:0,kind:'fake'}]]){const v=snapshot(s);edit(v);assert.throws(()=>restore(s.config,v),/Recovery unavailable/);}});
test('surface artwork does not damage aircraft; aircraft does',()=>{for(const [kind,expected] of [['ship',100],['shore',100],['fighter',80]]){const s=createRun();s.player.protection=0;s.enemies=[{id:'test',kind,x:320,baseX:320,y:299,w:40,h:40,hp:80,age:0,nextAttack:900,phase:0}];step(s);assert.equal(s.health,expected);}});
test('full authored timeline stays bounded with deterministic evasive input',()=>{const s=createRun({loadout:['armor']});for(let i=0;i<18000&&!s.outcome;i++){if(s.health<30)s.player.protection=60; // stress harness, not a playability claim
step(s,{right:Math.floor(i/120)%2===0,left:Math.floor(i/120)%2===1});assert.ok(s.hostile.length<=64&&s.friendly.length<=96);assert.ok(s.enemies.length<=12);}assert.ok(s.outcome);});
test('baseline and upgraded aircraft can mechanically complete boss within the 75-second boss section',()=>{for(const loadout of [[],['agility','armor','weapons']]){const s=createRun({loadout});s.tick=s.levelTick=13499;s.cursor=LEVEL.findIndex(e=>e.at>=BOSS_SECONDS);step(s);for(let i=0;i<4500&&!s.outcome;i++){const b=s.boss,target=b.x+(b.guns[0]>0?-180:b.guns[1]>0?180:0);step(s,{left:s.player.x>target+2,right:s.player.x<target-2});}assert.equal(s.outcome,'success');assert.equal(s.lives,3);assert.ok(s.tick<18000);}});

test('five-minute level doubles combatants and retains six unique supplies',()=>{assert.equal(T.limit/T.hz,300);assert.equal(T.speed,198);assert.equal(LEVEL.filter(e=>e.xs&&e.kind!=='supply').reduce((sum,e)=>sum+e.xs.length,0),64);assert.equal(LEVEL.filter(e=>e.kind==='boss').length,1);assert.equal(LEVEL.filter(e=>e.kind==='supply').length,6);assert.deepEqual(LEVEL.filter(e=>e.checkpoint).map(e=>e.at),[150,225]);const s=createRun();for(let i=0;i<18000;i++){s.player.protection=60;step(s,{left:true});if(i===17998)assert.equal(s.outcome,null);}assert.equal(s.outcome,'escape_lesser');assert.equal(s.tick,18000);assert.equal(s.counters.capDeferrals,0);});
