import test from 'node:test';
import assert from 'node:assert/strict';
import {QuestSession} from './authenticated-session.mjs';
import {enterAssisted,chooseAssisted,snapshot} from '../public/games/aerial-shooter/core.js';
import {coastalScene,COASTAL_ESCAPE} from '../public/cartridges/coastal-escape.js';
import {gateNames} from '../public/cartridges.js';
const ctx=()=>{const data=new Map();return {storage:{get:async k=>structuredClone(data.get(k)),put:async(k,v)=>data.set(k,structuredClone(v)),setAlarm:async()=>{}},blockConcurrencyWhile:fn=>fn()};};
async function call(r,path,body){const res=await r.fetch(new Request(`https://test${path}`,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{}));return {...await res.json(),status:res.status};}
const command=(r,type,extra={})=>call(r,'/command',{type,commandId:crypto.randomUUID(),...extra});
async function setup(gates=3,total=gates){const context=ctx(),r=new QuestSession(context);await call(r,'/init',{code:'COAST',teacherKey:'teacher',config:{cartridgeId:'coastal-escape',gateCount:gates,teamNames:['Crew'],modules:[{id:'number.gcf',itemCount:total,band:'beginner'}]}});for(const id of ['a','b'])await command(r,'student.join',{deviceId:id,alias:id,teamPin:r.state.teams['team-1'].pin});await command(r,'teacher.start',{teacherKey:'teacher'});for(const id of ['a','b'])await command(r,'briefing.ready',{deviceId:id});return {r,context};}
async function solve(r){const t=r.state.teams['team-1'];const stage=t.stage,index=t.gateIndex;for(const id of ['a','b']){for(let n=0;n<50;n++){await call(r,`/state?deviceId=${id}`);const s=r.state.students[id];if(s.gateComplete||t.stage!==stage||t.gateIndex!==index)break;const result=await command(r,'math.submit',{deviceId:id,answer:s.currentItem.answer});assert.equal(result.feedback?.correct,true);}}}
const lead=r=>r.members('team-1')[r.state.teams['team-1'].leadIndex%2].id;
async function vote(r,choice){for(const id of ['a','b'])assert.equal((await command(r,'choice.vote',{deviceId:id,choice})).status,200);assert.equal((await command(r,'choice.resolve',{deviceId:lead(r)})).status,200);}
async function market(r,route='operator'){await solve(r);await vote(r,route);assert.equal(r.state.teams['team-1'].stage,'gate');while(r.state.teams['team-1'].stage==='gate')await solve(r);}
async function launch(r){for(const id of ['a','b']){assert.equal((await command(r,'market.propose',{deviceId:id,items:['agility']})).status,200);await command(r,'market.ready',{deviceId:id});}await command(r,'market.commit',{deviceId:lead(r)});const out=await command(r,'market.continue',{deviceId:lead(r)});assert.equal(out.status,200);assert.equal(r.state.teams['team-1'].stage,'minigame');}
async function flight(r,id,type,state){const run=r.state.teams['team-1'].runs[id];return command(r,type,{deviceId:id,runId:run.runId,configRevision:run.config.configRevision,seq:run.seq+1,snapshot:state||run.snapshot});}
test('Coastal 3/4/5 gates, both routes, all endings, personal assisted results and restored classroom records',async()=>{
 for(const gates of [3,4,5])for(const route of ['operator','records']){
  const {r,context}=await setup(gates);await market(r,route);await launch(r);const t=r.state.teams['team-1'];const accuracy=r.state.students.a.firstAttemptCorrect;
  assert.equal(t.runs.a.config.loadout[0],'agility');assert.equal(t.runs.a.snapshot.speed,undefined);assert.equal(t.finaleDeadline-t.flightWindow.openedAt,300000);
  for(const id of ['a','b']){assert.equal((await flight(r,id,'aerial.start')).status,200);const s=structuredClone(t.runs[id].snapshot);enterAssisted(s);chooseAssisted(s,0);chooseAssisted(s,1);chooseAssisted(s,0);const result=await flight(r,id,'aerial.complete',snapshot(s));assert.equal(result.status,200,result.error);}
  assert.equal(t.stage,'finale');const ending=['deliver','exchange','destroy'][gates-3];await vote(r,ending);assert.equal(t.stage,'victory');assert.equal(r.state.students.a.firstAttemptCorrect,accuracy);assert.equal(r.report().gameplayEvidence.length,2);
  const scene=coastalScene(COASTAL_ESCAPE,t,gateNames(COASTAL_ESCAPE,gates),r.members(t.id));assert.ok(scene.paragraphs.some(p=>p.includes(route==='operator'?'Mara stays':'recovered records')));
  const restored=new QuestSession(context);await restored.ready;assert.equal(restored.state.teams[t.id].finalAction,ending);
 }
});
test('Coastal rejects cross-player, legacy minigame and unearned upgrades; closure preserves votes',async()=>{const {r}=await setup();await market(r);assert.equal((await command(r,'market.propose',{deviceId:'a',items:['agility','hull']})).status,400);await launch(r);const t=r.state.teams['team-1'],b=t.runs.b;assert.equal((await command(r,'aerial.start',{deviceId:'a',runId:b.runId,configRevision:b.config.configRevision,seq:1,snapshot:b.snapshot})).status,400);assert.equal((await command(r,'minigame.start',{deviceId:'a'})).status,400);await command(r,'teacher.advanceFinale',{teacherKey:'teacher',teamId:t.id});assert.equal(t.stage,'finale');assert.ok(Object.values(t.runs).every(r=>r.outcome==='teacher_advanced'));await vote(r,'destroy');assert.equal(t.stage,'victory');});
test('Coastal teacher pause shifts deadline once; alarm closes absent flights',async()=>{const {r}=await setup();await market(r);await launch(r);const t=r.state.teams['team-1'],original=Date.now;let now=Date.now();Date.now=()=>now;try{const deadline=t.finaleDeadline;await command(r,'teacher.pause',{teacherKey:'teacher'});now+=20000;await r.alarm();assert.equal(t.stage,'minigame');await command(r,'teacher.pause',{teacherKey:'teacher'});assert.equal(t.finaleDeadline,deadline+20000);now=t.finaleDeadline+1;await r.alarm();assert.equal(t.stage,'finale');assert.ok(Object.values(t.runs).every(r=>r.outcome==='window_closed'));}finally{Date.now=original;}});
test('Unequal gate loads require explicit extra-upgrade count and teacher setting enables it',async()=>{const {r}=await setup(3,4);await market(r);assert.equal((await command(r,'equipment.extend',{deviceId:lead(r)})).status,400);await command(r,'teacher.setSupply',{teacherKey:'teacher',teamId:'team-1',enabled:true,count:2});assert.equal((await command(r,'equipment.extend',{deviceId:lead(r)})).status,200);assert.equal(r.state.extensions.at(-1).count,2);});
