import test from 'node:test';
import assert from 'node:assert/strict';
import {QuestSession} from './authenticated-session.mjs';
import {newRun,step,damagePlayer,restoreRun,clearLine} from '../public/nightfall-core.js';
import {createState,completeTask} from '../public/games/nightfall/simulation.js';
const ctx=()=>{const data=new Map();return {storage:{get:async k=>structuredClone(data.get(k)),put:async(k,v)=>data.set(k,structuredClone(v))},blockConcurrencyWhile:fn=>fn()};};
async function call(r,path,body){const res=await r.fetch(new Request(`https://test${path}`,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:{}));return {...await res.json(),status:res.status};}
async function command(r,type,extra={}){return call(r,'/command',{type,commandId:crypto.randomUUID(),...extra});}
async function setup(gates=3){const context=ctx(),r=new QuestSession(context);await call(r,'/init',{code:'NIGHT7',teacherKey:'teacher',config:{cartridgeId:'nightfall',gateCount:gates,teamNames:['Crew','Empty'],modules:[{id:'number.gcf',itemCount:gates,band:'beginner'}]}});for(const id of ['a','b'])await command(r,'student.join',{deviceId:id,alias:id,teamPin:r.state.teams['team-1'].pin});await command(r,'teacher.start',{teacherKey:'teacher'});for(const id of ['a','b'])await command(r,'briefing.ready',{deviceId:id});return {r,context};}
async function solve(r){for(const id of ['a','b']){await call(r,`/state?deviceId=${id}`);const result=await command(r,'math.submit',{deviceId:id,answer:r.state.students[id].currentItem.answer});assert.equal(result.feedback?.correct,true);}}
async function vote(r,choice){for(const id of ['a','b'])await command(r,'choice.vote',{deviceId:id,choice});const lead=r.members('team-1')[r.state.teams['team-1'].leadIndex%2];assert.equal((await command(r,'choice.resolve',{deviceId:lead.id})).status,200);if(r.state.teams['team-1'].stage==='rescue')await command(r,'teacher.closeRescue',{teacherKey:'teacher',teamId:'team-1'});}
async function toFinale(r,gates=3){await solve(r);await vote(r,'clinic');for(let i=1;i<gates;i++)await solve(r);for(const id of ['a','b']){await command(r,'market.propose',{deviceId:id,items:['vest']});await command(r,'market.ready',{deviceId:id});}await command(r,'market.commit',{deviceId:'b'});await command(r,'market.continue',{deviceId:'b'});assert.equal(r.state.teams['team-1'].currency,40);}
test('Nightfall runs full 3/4/5 gate journeys with all work and independent results',async()=>{
 for(const gates of [3,4,5]){const {r,context}=await setup(gates);await toFinale(r,gates);const team=r.state.teams['team-1'];assert.equal(Object.keys(r.state.teams).length,1);assert.equal(team.stage,'minigame');assert.equal(team.runs.a.loadout.join('|'),'vest');
 const before=r.state.students.a.firstAttemptCorrect;
 for(const id of ['a','b']){const run=team.runs[id];await command(r,'minigame.start',{deviceId:id,runId:run.runId,configRevision:run.configRevision,mode:'action'});const snapshot=createState(run.loadout);if(id==='a')for(const task of ['fuse','power','keys','battery','installed','escape'])completeTask(snapshot,task);else {snapshot.outcome='lost';snapshot.health=0;}const result=await command(r,'minigame.complete',{deviceId:id,runId:run.runId,configRevision:run.configRevision,seq:1,activeElapsedMs:0,outcome:id==='a'?'success':'lost',snapshot});assert.ok(!result.error,result.error);}
 assert.equal(team.stage,'finale');await vote(r,'broadcast');assert.equal(team.stage,'victory');assert.equal(r.state.students.a.firstAttemptCorrect,before);assert.equal(r.report().gameplayEvidence.length,2);
 const restored=new QuestSession(context);await restored.ready;assert.equal(restored.state.teams['team-1'].stage,'victory');assert.equal(restored.report().session.cartridge,'Nightfall: Last Bus Out');}
});
test('Nightfall rejects unearned baskets, stale stage commands and another player run',async()=>{const {r}=await setup();await solve(r);await vote(r,'depot');await solve(r);await solve(r);assert.equal((await command(r,'market.propose',{deviceId:'a',items:['carbine','vest']})).status,400);assert.equal((await command(r,'market.commit',{deviceId:'a'})).status,400);for(const id of ['a','b']){await command(r,'market.propose',{deviceId:id,items:['vest']});await command(r,'market.ready',{deviceId:id});}await command(r,'market.commit',{deviceId:'b'});await command(r,'market.continue',{deviceId:'b'});assert.equal((await command(r,'market.commit',{deviceId:'b'})).status,400);const b=r.state.teams['team-1'].runs.b;assert.equal((await command(r,'minigame.start',{deviceId:'a',runId:b.runId,configRevision:b.configRevision,mode:'action'})).status,400);const view=await call(r,'/state?deviceId=a');assert.equal(view.teams[0].finale.results,undefined);assert.notEqual(view.teams[0].members[1].id,'b');});
test('deadline, teacher pause and teacher advancement settle missing players',async()=>{const {r}=await setup();await toFinale(r);const t=r.state.teams['team-1'];t.finaleDeadline=Date.now()-1;await command(r,'teacher.pause',{teacherKey:'teacher'});assert.equal(t.stage,'finale');const {r:r2}=await setup();await toFinale(r2);await command(r2,'teacher.advanceFinale',{teacherKey:'teacher',teamId:'team-1'});assert.ok(Object.values(r2.state.teams['team-1'].runs).every(x=>x.outcome==='teacher_advanced'));});
test('equipment has concrete, independent effects and cannot recharge on restore',()=>{const a=newRun(['vest','medkit']),b=newRun(['vest','medkit']);damagePlayer(a);assert.equal(a.vest,1);assert.equal(a.health,3);assert.equal(b.vest,2);a.immune=0;damagePlayer(a);a.immune=0;damagePlayer(a);a.immune=0;damagePlayer(a);assert.equal(a.medkit,0);assert.equal(a.health,2);assert.equal(restoreRun(a,a.loadout,'clinic').medkit,0);assert.equal(newRun(['ammo-pouch']).ammo,60);assert.equal(newRun(['carbine']).damage,2);});
test('baseline no-shooting route is completable; movement is normalized and walls block shots',()=>{const s=newRun();const move=(x,y)=>{for(let i=0;i<1500&&Math.hypot(s.x-x,s.y-y)>5&&!s.outcome;i++)step(s,{right:s.x<x-3,left:s.x>x+3,down:s.y<y-3,up:s.y>y+3});};move(80,160);move(832,160);move(832,544);assert.equal(s.outcome,'success');assert.equal(s.shots,0);assert.ok(s.time<90);assert.equal(clearLine({x:80,y:300},{x:400,y:300}),false);const a=newRun(),b=newRun();step(a,{right:true});step(b,{right:true,up:true});assert.ok(Math.abs(Math.hypot(b.x-80,b.y-544)-(a.x-80))<.001);});
