import test from 'node:test';import assert from 'node:assert/strict';
import {createState,step,completeTask,navigationField,move,SHOTGUN} from '../public/games/nightfall/simulation.js';
import {createHaven} from '../public/games/nightfall/false-haven-adapter.js';
import {worldFor,solid,lineClear} from '../public/games/nightfall/world.js';
import {HAVEN_TASKS,havenSwitch,havenTick,trolleyRect} from '../public/games/nightfall/false-haven-world.js';
const fresh=()=>createHaven({runId:'test',loadout:[]});
function reachable(s){const w=worldFor(s).WORLD,C=w.width/32,R=w.height/32,pass=new Uint8Array(C*R);for(let y=0;y<R;y++)for(let x=0;x<C;x++)pass[y*C+x]=!solid(s,x*32+16,y*32+16,10);const start=Math.floor(s.y/32)*C+Math.floor(s.x/32),seen=new Set([start]),queue=[start];for(let i=0;i<queue.length;i++){const k=queue[i],x=k%C,y=Math.floor(k/C);for(const [a,b]of [[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){const n=b*C+a;if(a>=0&&a<C&&b>=0&&b<R&&pass[n]&&!seen.has(n)){seen.add(n);queue.push(n);}}}return {count:seen.size,seen,C};}
function pathTo(s,target){const {WORLD:w}=worldFor(s),C=w.width/32,R=w.height/32,start=Math.floor(s.y/32)*C+Math.floor(s.x/32),parents=new Map([[start,null]]),q=[start];let end;
 for(let i=0;i<q.length;i++){const k=q[i],x=k%C,y=Math.floor(k/C),p={x:x*32+16,y:y*32+16};if(Math.hypot(p.x-target.x,p.y-target.y)<50&&lineClear(s,p,target)){end=k;break;}for(const [a,b]of[[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){const n=b*C+a;if(a<0||a>=C||b<0||b>=R||parents.has(n)||solid(s,a*32+16,b*32+16,10))continue;parents.set(n,k);q.push(n);}}
 assert.notEqual(end,undefined,'reachable objective '+target.id);const path=[];for(let k=end;k!==null;k=parents.get(k))path.unshift({x:k%C*32+16,y:Math.floor(k/C)*32+16});return path;
}
test('new world is 2.25x bounds and at least twice reachable area',()=>{const a=createState(),b=fresh();for(const s of [a,b]){for(const t of worldFor(s).TASKS)s.tasks[t.id]=true;for(const id of Object.keys(s.doors))s.doors[id].closed=false;for(const w of worldFor(s).WINDOWS)s.windows[w.id]=true;}b.haven.trolleyProgress=1;const ca=reachable(a).count,cb=reachable(b).count;console.log('AREA',JSON.stringify({chapter1Cells:ca,chapter2Cells:cb,ratio:cb/ca,boundsRatio:2.25}));assert.ok(cb>=ca*2);assert.equal(navigationField(b,{x:3600,y:1800}).length,7200);});
test('all authored actors spawn in free space, roster stays the same',()=>{const s=fresh();assert.equal(s.enemies.length,46);assert.deepEqual(new Set(s.enemies.map(e=>e.kind)),new Set(['shambler','runner','crawler','brute']));for(const e of s.enemies)assert.equal(solid(s,e.x,e.y),false,e.id);assert.equal(SHOTGUN.pellets,7);});
test('physical movement and real Use input finish required route without ammunition',()=>{const s=fresh();s.enemies=[];s.ammo=0;let distance=0;for(const task of HAVEN_TASKS){if(task.automatic){for(let i=0;i<400&&!s.tasks[task.id];i++)step(s,{},1/60);assert.ok(s.tasks[task.id]);continue;}for(const point of pathTo(s,task)){let n=0;while(Math.hypot(s.x-point.x,s.y-point.y)>2&&n++<120){s.angle=Math.atan2(point.y-s.y,point.x-s.x);step(s,{up:true},1/60);distance+=100/60;}assert.ok(n<120,'no collision stall '+task.id);}for(let i=0;i<400&&!s.tasks[task.id];i++)step(s,{interact:true},1/60);step(s,{},1/60);assert.ok(s.tasks[task.id],task.id);}console.log('ROUTE',JSON.stringify({activeSeconds:s.time,walkingDistance:distance}));assert.equal(s.outcome,'success');assert.ok(s.time<300);assert.equal(s.shots,0);});
test('puzzle ordering, occupied track and local speaker cooldown remain recoverable',()=>{const s=fresh();assert.equal(completeTask(s,'power_depot'),false);completeTask(s,'generator_online');completeTask(s,'power_pump');s.time=6;havenTick(s,6);assert.ok(s.tasks.passage_drained);completeTask(s,'service_shortcut');completeTask(s,'power_depot');s.enemies=[];s.x=3220;s.y=820;assert.equal(completeTask(s,'trolley_parked'),false);s.y=912;assert.equal(completeTask(s,'trolley_parked'),true);havenTick(s,2);assert.equal(s.tasks.trolley_parked,true);assert.equal(trolleyRect(s).x,3456);assert.equal(havenSwitch(s,'speaker'),true);assert.equal(havenSwitch(s,'speaker'),false);s.time+=27;assert.equal(havenSwitch(s,'speaker'),true);});
test('save restores topology, ammo, elapsed time and terminal state without cross-chapter mutation',()=>{const s=fresh();completeTask(s,'generator_online');completeTask(s,'power_pump');s.time=11;havenTick(s,6);completeTask(s,'service_shortcut');s.ammo=3;s.x=2800;s.y=1408;s.haven.trapClosed=true;const r=createHaven({runId:'test',snapshot:structuredClone(s)});assert.equal(r.x,2800);assert.equal(r.ammo,3);assert.equal(r.time,11);assert.equal(r.tasks.service_shortcut,true);assert.equal(r.haven.trapClosed,true);r.time=299.99;step(r,{},1/60);assert.equal(r.outcome,'timed_out');const end=createHaven({runId:'test',snapshot:r});assert.equal(end.outcome,'timed_out');assert.equal(createState().revision,'nightfall-city-5');assert.equal(createHaven({runId:'different',snapshot:s}).time,0);});
