import test from 'node:test';
import assert from 'node:assert/strict';
import {BrawlModel} from '../src/cartridges/journey/model.js';
import {LIMITS} from '../public/games/journey/config.js';
const create=(n=2)=>new BrawlModel({runId:'run',roomCode:'TEST01',teamId:'team-1',expiresAt:1e9,members:Array.from({length:n},(_,i)=>({id:'p'+i,alias:'Agent '+i}))},0);
const heroes=['wukong','bajie','wujing','tang','prince'];
function select(m,i,now=0){m.connect('p'+i,now);m.reserve('p'+i,heroes[i],now);}
function start(n=1){const m=create(n);for(let i=0;i<n;i++){select(m,i);m.ready('p'+i,[],0);}m.advance(3000);return m;}

test('all-ready launches early; active time excludes ready and countdown',()=>{const m=create();select(m,0);select(m,1);m.ready('p0',['reserve'],100);m.ready('p1',['power'],500);assert.equal(m.s.phase,'launch');assert.equal(m.s.activeMs,0);m.advance(3500);assert.equal(m.s.phase,'running');assert.equal(m.s.activeMs,0);assert.equal(m.player('p0').magic,2);});
test('one-minute expiry selects ready subset and freezes party size',()=>{const m=create(3);select(m,0);m.ready('p0',[],100);m.advance(60000);assert.equal(m.s.phase,'launch');assert.deepEqual(m.s.starters,['p0']);selectLate(m);function selectLate(m){m.connect('p1',60001);assert.throws(()=>m.reserve('p1','bajie',60001),/closed/);assert.throws(()=>m.ready('p1',[],60001),/closed/);}assert.equal(m.s.starters.length,1);});
test('zero-ready expiry stays unstarted and late readiness gets no new minute',()=>{const m=create(1);m.advance(70000);assert.equal(m.s.phase,'ready');assert.equal(m.s.readyMs,0);select(m,0,70000);assert.throws(()=>m.grant('p0',2,70000),/closed/);m.ready('p0',[],70001);assert.equal(m.s.phase,'launch');});
test('optional entitlement is personal and closed at authoritative cutoff',()=>{const m=create();select(m,0);select(m,1);m.grant('p0',2,100);assert.equal(m.player('p1').slots,1);assert.throws(()=>m.ready('p1',['power','focus'],101),/earned/);m.advance(60000);assert.throws(()=>m.grant('p0',3,60000),/closed/);});
test('unique hero reservations and invalid upgrades cannot be bypassed',()=>{const m=create();select(m,0);m.connect('p1',0);assert.throws(()=>m.reserve('p1','wukong',0),/already/);assert.throws(()=>m.reserve('p1','nezha',0),/available/);assert.throws(()=>m.ready('p0',['not-earned'],0),/earned/);assert.throws(()=>m.grant('p0',3,0),/entitlement/);});
test('input authority rejects stale epochs, replayed edges and forged movement',()=>{const m=start(),p=m.player('p0'),epoch=p.epoch;p.magic=3;m.input('p0',epoch,{seq:1,x:0,y:0,attack:false,magic:true},3001);assert.equal(p.magic,2);m.input('p0',epoch,{seq:1,x:0,y:0,attack:false,magic:true},4000);assert.equal(p.magic,2);assert.throws(()=>m.input('p0',epoch,{seq:2,x:99,y:0,attack:false},4001),/Invalid input/);m.input('p0',epoch-1,{seq:2,x:1,y:0,attack:false},4002);assert.equal(p.input.x,0);});
test('network lease stops stale movement but permits refreshed stationary held input',()=>{const m=start(),p=m.player('p0'),e=p.epoch;m.s.enemies=[];m.input('p0',e,{seq:1,x:1,y:0,attack:false},3001);const x=p.x;m.advance(3200);assert.ok(p.x>x);m.advance(3500);const stopped=p.x;m.advance(4000);assert.equal(p.x,stopped);for(let i=0;i<10;i++)m.input('p0',e,{seq:i+2,x:1,y:0,attack:false},4050+i*50);assert.ok(p.x>stopped);});
test('teacher pause freezes readiness, launch, active time and recovery independently',()=>{const m=create();m.setPause('session',true,1000);m.advance(20000);assert.equal(m.s.readyMs,59000);m.setPause('team',true,20000);m.setPause('session',false,21000);m.advance(25000);assert.equal(m.s.readyMs,59000);m.setPause('team',false,26000);select(m,0,26000);select(m,1,26000);m.ready('p0',[],26000);m.ready('p1',[],26000);m.setPause('team',true,27000);m.advance(29000);assert.equal(m.s.launchMs,2000);m.setPause('team',false,29000);m.advance(31000);assert.equal(m.s.phase,'running');});
test('single disconnect continues; all-team recovery preserves elapsed and resources',()=>{const m=start(2);m.s.enemies=[];m.player('p0').hp=47;m.player('p0').magic=0;m.disconnect('p0',1,3200);m.advance(3400);assert.equal(m.s.phase,'running');m.disconnect('p1',1,3400);const elapsed=m.s.activeMs;m.advance(6000);assert.equal(m.s.phase,'recovery');assert.equal(m.s.activeMs,elapsed);const epoch=m.connect('p0',6100);assert.equal(m.s.phase,'running');assert.equal(m.player('p0').hp,47);assert.equal(m.player('p0').magic,0);m.disconnect('p0',epoch-1,6200);assert.equal(m.player('p0').connected,true);});
test('all-team recovery timeout is interrupted and a duplicate terminal cannot overwrite it',()=>{const m=start();m.disconnect('p0',1,4000);m.advance(19001);assert.equal(m.s.result.outcome,'interrupted');assert.equal(m.s.result.reason,'connection_timeout');m.finish('victory','forged');assert.equal(m.s.result.outcome,'interrupted');});
test('death retains upgrades/magic and third life ends in defeat',()=>{const m=start(),p=m.player('p0');m.s.enemies=[];p.upgrades=['power'];p.magic=2;m.hurt(p,100);assert.equal(p.lives,2);m.advance(5000);assert.equal(p.hp,100);assert.equal(p.magic,2);assert.deepEqual(p.upgrades,['power']);assert.equal(p.protectionMs,2000);p.protectionMs=0;p.hurtMs=0;m.hurt(p,100);m.advance(7000);p.protectionMs=0;p.hurtMs=0;m.hurt(p,100);m.advance(7001);assert.equal(p.lives,0);assert.equal(m.s.result.outcome,'defeat');});
test('only the collector receives a pickup and a full meter leaves it',()=>{const m=start(2),a=m.player('p0'),b=m.player('p1');m.s.enemies=[];a.x=b.x=400;a.y=b.y=245;a.magic=a.capacity;b.magic=0;m.s.pickups=[{id:'one',kind:'magic',x:400,y:245,taken:false}];m.advance(3001);assert.equal(a.magic,3);assert.equal(b.magic,1);assert.equal(m.s.pickups[0].taken,true);m.advance(3002);assert.equal(b.magic,1);});
test('active deadline produces retreat with no late victory and expiry interrupts',()=>{const m=start();m.s.enemies=[];m.advance(183000);assert.equal(m.s.activeMs,LIMITS.active);assert.equal(m.s.result.outcome,'retreat');const other=start();other.s.expiresAt=4000;other.advance(4000);assert.equal(other.s.result.reason,'session_expired');});
