import test from 'node:test';
import assert from 'node:assert/strict';
import {QuestSession} from '../src/worker.js';
import {BrawlRun} from '../src/cartridges/journey/durable-object.js';

function context(){const data=new Map();return {data,storage:{get:async k=>structuredClone(data.get(k)),put:async(k,v)=>data.set(k,structuredClone(v)),deleteAll:async()=>data.clear(),deleteAlarm:async()=>{},setAlarm:async()=>{}},blockConcurrencyWhile:fn=>fn(),waitUntil:p=>p.catch(()=>{}),getWebSockets:()=>[]};}
async function fixture(n=2){const runs=new Map(),ctx=context();let room;const env={COMBAT_PUBLIC_BASE:'http://127.0.0.1:8787',BRAWLS:{idFromName:x=>x,get:id=>{if(!runs.has(id))runs.set(id,new BrawlRun(context(),env));return runs.get(id);}},SESSIONS:{idFromName:x=>x,get:()=>room}};room=new QuestSession(ctx,env);
  const teacher=crypto.randomUUID(),keys=Object.fromEntries(Array.from({length:n+1},(_,i)=>['p'+i,crypto.randomUUID()]));
  async function call(path,body,key){const res=await room.fetch(new Request('https://session'+path,{method:body?'POST':'GET',headers:{'content-type':'application/json',...(key?{authorization:'Bearer '+key}:{})},...(body?{body:JSON.stringify(body)}:{})}));return {status:res.status,body:await res.json()};}
  const cmd=async(type,id,extra={})=>call('/command',{type,commandId:crypto.randomUUID(),deviceId:id,...extra},type.startsWith('teacher.')?teacher:keys[id]);
  await call('/init',{code:'JTTW01',teacherKey:teacher,config:{cartridgeId:'journey-west',teamNames:['Travelers'],gateCount:3,modules:[{id:'number.gcf',source:'preset',band:'beginner',itemCount:3}]}});
  const pin=room.state.teams['team-1'].pin;for(let i=0;i<n;i++)assert.equal((await cmd('student.join','p'+i,{teamPin:pin})).status,200);
  async function prepare(){await cmd('teacher.start');for(let i=0;i<n;i++)await cmd('briefing.ready','p'+i);for(let gate=0;gate<3;gate++)for(let i=0;i<n;i++){await call('/state?deviceId=p'+i,null,keys['p'+i]);const answer=room.state.students['p'+i].currentItem.answer;const r=await cmd('math.submit','p'+i,{answer});assert.equal(r.status,200,r.body.error);}return runs.get(room.state.teams['team-1'].journey.runId);}
  return {room,runs,ctx,cmd,call,prepare,teacher,keys,pin};
}
test('normal team code joining caps only Journey at five and allows authenticated rejoin',async()=>{const f=await fixture(5);assert.equal((await f.cmd('student.join','p5',{teamPin:f.pin})).status,400);assert.equal((await f.cmd('student.join','p0',{teamPin:f.pin})).status,200);assert.equal((await f.call('/state?deviceId=p0',null,'wrong')).status,403);});
test('required gates hand off once without extra team joining or academic completion shortcuts',async()=>{const f=await fixture();assert.equal((await f.cmd('journey.connect','p0')).status,400);const run=await f.prepare(),team=f.room.state.teams['team-1'];assert.equal(team.stage,'brawl');assert.equal(f.runs.size,1);assert.deepEqual(Object.keys(run.model.s.players),['p0','p1']);const id=team.journey.runId;await f.call('/state?deviceId=p0',null,f.keys.p0);assert.equal(team.journey.runId,id);const ticket=await f.cmd('journey.connect','p0');assert.equal(ticket.status,200);assert.ok(ticket.body.combatConnection.ticket);assert.ok(!ticket.body.combatConnection.url.includes(f.keys.p0));assert.equal(f.room.state.attempts.length,6);});
test('optional math earns a personal choice and keeps team inventory unchanged',async()=>{const f=await fixture(),run=await f.prepare();await f.cmd('journey.optional.start','p0');const student=f.room.state.students.p0,item=student.journeyPrep.current.item;assert.equal((await f.cmd('journey.optional.answer','p0',{itemId:item.id,answer:item.answer})).status,200);assert.equal(student.journeyPrep.earned,2);assert.equal(run.model.player('p0').slots,2);assert.equal(run.model.player('p1').slots,1);assert.deepEqual(f.room.state.teams['team-1'].inventory,[]);assert.equal(f.room.state.attempts.at(-1).purpose,'journey-personal-preparation');assert.equal(f.room.state.students.p1.itemsCompleted,3);});
test('teacher team controls and terminal result produce one separate engagement record',async()=>{const f=await fixture(1),run=await f.prepare();run.model.connect('p0',Date.now());run.model.reserve('p0','wukong',Date.now());await f.cmd('journey.ready','p0',{upgrades:['power']});await f.cmd('teacher.journey.pause',null,{teamId:'team-1'});assert.equal(run.model.paused,true);await f.cmd('teacher.journey.resume',null,{teamId:'team-1'});assert.equal(run.model.paused,false);const before=f.room.state.students.p0.firstAttemptCorrect;await f.cmd('teacher.journey.end',null,{teamId:'team-1'});assert.equal(f.room.state.teams['team-1'].journeyResult.outcome,'interrupted');assert.equal(f.room.report().gameplayEvidence.length,1);assert.equal(f.room.state.students.p0.firstAttemptCorrect,before);assert.match(f.room.reportCsv(),/JOURNEY/);await f.cmd('teacher.journey.end',null,{teamId:'team-1'});assert.equal(f.room.report().gameplayEvidence.length,1);clearInterval(run.timer);});
test('forged result rejected; hosted session deletion includes child runs',async()=>{const f=await fixture(1),run=await f.prepare();const r=await f.call('/journey-result',{resultKey:'wrong',result:{runId:run.model.s.runId}});assert.equal(r.status,403);const deletion=await f.call('/delete',{},f.teacher);assert.equal(deletion.status,200);assert.equal(run.model,null);assert.equal((await f.call('/state?deviceId=p0',null,f.keys.p0)).status,410);});
