import test from 'node:test';import assert from 'node:assert/strict';
import {BrawlModel} from '../src/cartridges/journey/model.js';
import {specialStep} from '../src/cartridges/journey/specials.js';
function setup(hero){const m=new BrawlModel({runId:'special',teamId:'t',expiresAt:1e9,members:[{id:'p'}]},0);m.connect('p',0);m.reserve('p',hero,0);m.ready('p',[],0);m.startScene();m.s.level.queue=[];const p=m.player('p');p.x=300;p.y=300;const e={id:'e',kind:'brute',x:340,y:300,hp:500,maxHp:500,phase:'recover',timer:1e6,facing:-1};m.s.enemies=[e];return {m,p,e};}
for(const [hero,damage,duration] of [['wukong',72,2400],['bajie',60,900],['wujing',54,1400],['tang',40,900]])test(hero+' timed damage, one charge and completion',()=>{const {m,p,e}=setup(hero);m.special(p);assert.equal(e.hp,500);m.special(p);assert.equal(p.magic,0);for(let t=0;t<duration;t+=50)specialStep(m,p,50);assert.equal(e.hp,500-damage);assert.equal(p.specialState,null);});
test('pause freezes special; death cancels; ordinary attacks cannot overlap cast',()=>{const {m,p,e}=setup('wukong');m.special(p);m.setPause('teacher',true,0);m.advance(900);assert.equal(p.specialState.age,0);m.setPause('teacher',false,900);p.input.attack=true;p.lastInput=900;m.advance(1000);assert.equal(e.hp,500);m.hurt(p,100);assert.equal(p.specialState,null);});
test('river wave hits a target once, passes forward and never pushes boss',()=>{const {m,p,e}=setup('wujing');e.kind='nezha';e.lastStagger=-2000;const x=e.x;m.special(p);for(let i=0;i<30;i++)specialStep(m,p,50);assert.equal(e.hp,446);assert.equal(e.x,x);});
test('lotus ward does not heal or extend an existing shield',()=>{const {m,p}=setup('tang');p.hp=40;p.shield=5;p.shieldMs=700;m.special(p);specialStep(m,p,300);assert.equal(p.hp,40);assert.equal(p.shield,20);assert.equal(p.shieldMs,700);});
test('disconnect cancels delayed damage without refund',()=>{const {m,p,e}=setup('bajie');m.special(p);p.connected=false;specialStep(m,p,500);assert.equal(p.specialState,null);assert.equal(e.hp,500);assert.equal(p.magic,0);});
