import test from 'node:test';
import assert from 'node:assert/strict';
import {QuestSession} from './authenticated-session.mjs';
import {createState,step,completeTask,restoreState,damage} from '../public/games/nightfall/simulation.js';
import {WORLD,TASKS,solid,lineClear} from '../public/games/nightfall/world.js';
const call=async(r,type,extra={})=>{const res=await r.fetch(new Request('https://test/command',{method:'POST',body:JSON.stringify({type,commandId:crypto.randomUUID(),...extra})}));return res.json();};
async function room(cartridgeId='vault-7'){
 const data=new Map(),r=new QuestSession({storage:{get:async k=>data.get(k),put:async(k,v)=>data.set(k,structuredClone(v))},blockConcurrencyWhile:fn=>fn()});
 await r.fetch(new Request('https://test/init',{method:'POST',body:JSON.stringify({code:'TEST08',teacherKey:'secret',config:{cartridgeId,gateCount:3,teamNames:['Crew'],modules:[{id:'number.gcf',itemCount:6,band:'beginner'}]}})}));
 for(const deviceId of ['a','b'])await call(r,'student.join',{deviceId,alias:deviceId,teamPin:r.state.teams['team-1'].pin});await call(r,'teacher.start',{teacherKey:'secret'});for(const deviceId of ['a','b'])await call(r,'briefing.ready',{deviceId});return r;
}
const payload={teacherKey:'secret',count:3,placement:'current',policy:'keep',moduleIds:['number.gcf'],studentIds:['a']};
async function add(r,extra={}){const args={...payload,...extra},p=await call(r,'teacher.previewExtension',args);assert.ok(p.extensionPreview,p.error);return call(r,'teacher.extend',{...args,expectedRevision:p.extensionPreview.revision});}
test('live extension retains issued item, completed evidence and adds only selected student workload',async()=>{
 const r=await room(),a=r.state.students.a,b=r.state.students.b;const issued=r.ensureItem(a),before=structuredClone(a.plan);await add(r);assert.equal(a.currentItem.id,issued.id);assert.equal(a.assignedTotal,9);assert.equal(b.assignedTotal,6);assert.deepEqual(a.plan.slice(0,2),before.slice(0,2));assert.equal(a.gateLoads[0],5);assert.equal(a.plan[2].extensionBatchId,r.state.extensions[0].id);assert.equal(r.report().students.find(s=>s.studentId==='a')?.totalQuestions??a.assignedTotal,9);
});
test('live extension preview rejects stale revision, ended sessions and missing teacher credential',async()=>{const r=await room(),p=await call(r,'teacher.previewExtension',payload);r.bump();assert.match((await call(r,'teacher.extend',{...payload,expectedRevision:p.extensionPreview.revision})).error,/changed/);assert.match((await call(r,'teacher.previewExtension',{...payload,teacherKey:'wrong'})).error,/Teacher/);await call(r,'teacher.end',{teacherKey:'secret'});assert.match((await call(r,'teacher.previewExtension',payload)).error,/active/);});
test('future gate extension leaves current gate unchanged and supports private difficulty override',async()=>{const r=await room();await add(r,{placement:'next',policy:'challenge'});assert.deepEqual(r.state.students.a.gateLoads,[2,5,2]);assert.equal(r.state.students.a.plan[4].difficultyOverride,'challenge');assert.equal(r.state.students.b.gateLoads[1],2);});
test('Last Checkpoint restores pending narrative choice without erasing votes or inventory',async()=>{const r=await room(),t=r.state.teams['team-1'];t.stage='finale';t.gateIndex=2;t.finalVotes={a:'copy'};t.inventory=['scanner'];for(const s of r.members(t.id)){s.itemsCompleted=6;s.currentItem=null;}await add(r,{count:1,placement:'last'});assert.equal(t.stage,'gate');assert.equal(r.state.students.b.gateComplete,true);const item=r.ensureItem(r.state.students.a);const result=await call(r,'math.submit',{deviceId:'a',answer:item.answer});assert.ok(!result.error,result.error);assert.equal(t.stage,'finale');assert.equal(t.finalVotes.a,'copy');assert.deepEqual(t.inventory,['scanner']);assert.equal(r.state.attempts[0].gateName,'Last Checkpoint');});
test('live extension skips students whose minigame has begun',async()=>{const r=await room('nightfall');Object.assign(r.state.teams['team-1'],{stage:'minigame',runs:{a:{status:'active'},b:{status:'active'}}});assert.match((await call(r,'teacher.previewExtension',payload)).error,/No selected/);});
test('Nightfall world is over five times previous area and contains 34 ambient enemies and 8 storefront guards at Standard',()=>{const s=createState();assert.ok(WORLD.width*WORLD.height/(960*640)>5);assert.equal(s.enemies.length,42);assert.equal(s.ammo,12);assert.equal(createState(['ammo-pouch']).ammo,36);});
test('bus cannot complete until fuse, power, battery, installation and keys prerequisites',()=>{const s=createState();assert.equal(completeTask(s,'escape'),false);assert.equal(completeTask(s,'battery'),false);for(const id of ['fuse','power','keys','battery','installed','escape'])assert.equal(completeTask(s,id),true,id);assert.equal(s.outcome,'success');});
test('manual shot does not rotate toward a nearby enemy; no five-second or 90-second victory',()=>{const s=createState();s.enemies=[{...s.enemies[0],x:s.x+150,y:s.y,hp:2}];const angle=s.angle;step(s,{fire:true});assert.equal(s.angle,angle);assert.equal(s.bullets[0].angle,angle);assert.equal(s.ammo,11);s.time=95;step(s,{});assert.equal(s.outcome,null);});
test('optional rescue reduces local ambush without teleporting enemies',()=>{for(const rescue of [false,true]){const s=createState();if(rescue)completeTask(s,'survivor');for(const id of ['fuse','power','keys','battery'])completeTask(s,id);const before=s.enemies.filter(e=>!e.horde).map(e=>[e.x,e.y]);completeTask(s,'installed');assert.deepEqual(s.enemies.filter(e=>!e.horde).map(e=>[e.x,e.y]),before);assert.equal(s.enemies.filter(e=>e.phase==='investigate'&&!e.horde).length,rescue?1:3);}});
test('held interaction has duration and map tasks are accessible from spawn through unlocked geometry',()=>{const s=createState();s.enemies=[];const fuse=TASKS.find(t=>t.id==='fuse');s.x=fuse.x;s.y=fuse.y;step(s,{interact:true});assert.ok(!s.tasks.fuse);for(let i=0;i<220;i++)step(s,{interact:true});assert.equal(s.tasks.fuse,true);});
test('resource effects survive recovery and carbine changes actual projectile damage',()=>{const s=createState(['vest','medkit','carbine']);damage(s);assert.equal(s.vest,1);s.immune=0;damage(s);s.immune=0;damage(s);s.immune=0;damage(s);assert.equal(s.health,1);assert.equal(s.medkit,0);assert.equal(restoreState(s,s.loadout).medkit,0);assert.equal(s.damage,2);});
test('all essential objectives have traversable routes, with power enabling the garage',()=>{
 const s=createState();s.enemies=[];
 function route(target){const start=[Math.floor(s.x/16),Math.floor(s.y/16)],queue=[start],seen=new Set([start.join(',')]);for(let i=0;i<queue.length;i++){const [x,y]=queue[i];if(Math.hypot(x*16+8-target.x,y*16+8-target.y)<40)return true;for(const [nx,ny]of[[x-1,y],[x+1,y],[x,y-1],[x,y+1]]){const k=`${nx},${ny}`;if(nx<0||nx>=160||ny<0||ny>=80||seen.has(k)||solid(s,nx*16+8,ny*16+8,11))continue;seen.add(k);queue.push([nx,ny]);}}return false;}
 for(const id of ['fuse','power','keys','battery','installed','escape']){const t=TASKS.find(t=>t.id===id);assert.ok(route(t),id+' inaccessible');completeTask(s,id);}
});
