import test from 'node:test';
import assert from 'node:assert/strict';
import {QuestSession} from './authenticated-session.mjs';
import {checkItem,normalizeCustomItem,PRESET_MODULES,generatePresetItem} from '../src/math.js';
import {beginExtraction,settleExtractions} from '../src/extraction.js';
import {equipmentSlots} from '../src/engine/equipment.js';
import {StealthSimulation,RULES} from '../public/stealth-core.js';
import {createState,step,completeTask,activeAlarm,triggerDistraction,breakWindow,collectShotgun,restoreState,toggleDoor,SHOTGUN} from '../public/games/nightfall/simulation.js';
import {WINDOWS,solid,PROPS,propBounds} from '../public/games/nightfall/world.js';
const ctx=()=>{const data=new Map();return {storage:{get:async k=>structuredClone(data.get(k)),put:async(k,v)=>data.set(k,structuredClone(v))},blockConcurrencyWhile:f=>f()};};
async function request(r,path,body){const response=await r.fetch(new Request('https://test/'+path,body?{method:'POST',body:JSON.stringify(body)}:{}));return response.json();}
const cmd=(r,type,args={})=>request(r,'command',{type,commandId:crypto.randomUUID(),...args});
async function setup(cartridge='vault-7',size=2){const context=ctx(),r=new QuestSession(context);await request(r,'init',{code:'TEST92',teacherKey:'teacher',config:{cartridgeId:cartridge,gateCount:3,teamNames:['Crew'],modules:[{id:'number.gcf',itemCount:3,band:'beginner'}]}});for(let i=0;i<size;i++)await cmd(r,'student.join',{deviceId:'s'+i,teamPin:r.state.teams['team-1'].pin});await cmd(r,'teacher.start',{teacherKey:'teacher'});for(let i=0;i<size;i++)await cmd(r,'briefing.ready',{deviceId:'s'+i});return {r,t:r.state.teams['team-1'],context};}
async function solve(r,t){for(const m of r.members(t.id))while(!m.gateComplete){const q=r.ensureItem(m);assert.ok(q,'assigned item exists');const result=await cmd(r,'math.submit',{deviceId:m.id,answer:q.answer});assert.equal(result.feedback?.correct,true,result.error);}}
const lead=(r,t)=>r.members(t.id)[t.leadIndex%r.members(t.id).length].id;
async function market(r,t,cartridge){await solve(r,t);for(const m of r.members(t.id))await cmd(r,cartridge==='nightfall'?'choice.vote':'decision.vote',{deviceId:m.id,choice:cartridge==='nightfall'?'clinic':'corridor'});await cmd(r,cartridge==='nightfall'?'choice.resolve':'decision.resolve',{deviceId:lead(r,t)});await solve(r,t);if(cartridge==='nightfall')await solve(r,t);assert.equal(t.stage,'market');}
async function equip(r,t,items){for(const m of r.members(t.id)){assert.ok(!(await cmd(r,'market.propose',{deviceId:m.id,items})).error);assert.ok(!(await cmd(r,'market.ready',{deviceId:m.id})).error);}const id=crypto.randomUUID(),args={deviceId:lead(r,t),commandId:id};assert.ok(!(await cmd(r,'market.commit',args)).error);await cmd(r,'market.commit',args);assert.deepEqual([...t.inventory].sort(),[...items].sort());}
for(const cartridge of ['vault-7','nightfall'])test(`${cartridge}: actual commands unlock all seven loadout combinations and persist for all clients`,async()=>{
 const ids=cartridge==='nightfall'?['carbine','ammo-pouch','vest']:['scanner','toolkit','cloak'];
 for(let mask=1;mask<8;mask++){
  const {r,t,context}=await setup(cartridge),items=ids.filter((_,i)=>mask&(1<<i));await market(r,t,cartridge);
  assert.ok((await cmd(r,'market.continue',{deviceId:lead(r,t)})).error,'no implicit empty loadout');
  for(let i=1;i<items.length;i++){const answerCount=r.state.attempts.length;assert.ok(!(await cmd(r,'equipment.extend',{deviceId:lead(r,t)})).error);assert.equal(t.stage,'gate');assert.equal(equipmentSlots(t),i);await solve(r,t);assert.equal(t.stage,'market');assert.equal(equipmentSlots(t),i+1);assert.equal(r.state.attempts.length-answerCount,6);}
  await equip(r,t,items);assert.ok(!(await cmd(r,'market.continue',{deviceId:lead(r,t)})).error);
  if(cartridge==='vault-7'){await solve(r,t);assert.equal(t.stage,'code');await cmd(r,'code.submit',{deviceId:lead(r,t),code:t.cipher.secret});for(const m of r.members(t.id))await cmd(r,'finale.vote',{deviceId:m.id,choice:'isolate'});await cmd(r,'finale.resolve',{deviceId:lead(r,t)});assert.equal(t.stage,'extraction');assert.deepEqual([...t.extraction.loadout].sort(),[...items].sort());
   for(const m of r.members(t.id)){const projected=await request(r,'state?deviceId='+m.id);const config=projected.teams[0].extraction;const sim=new StealthSimulation(config);sim.start();sim.step({cloak:true,jam:true});assert.equal(sim.cloakUsed,items.includes('cloak'));assert.equal(sim.jams.length,items.includes('toolkit')?1:0);const recovery=new StealthSimulation(config,sim.summary());recovery.start();recovery.step({cloak:true,jam:true});assert.equal(recovery.jams.length,sim.jams.length);assert.equal(recovery.cloakUntil,0);}
   if(items.includes('scanner'))assert.ok(t.cipher.mappings.every(m=>m.status!=='corrupted'));
  }else{assert.equal(t.stage,'minigame');for(const m of r.members(t.id)){const run=t.runs[m.id];assert.deepEqual([...run.loadout].sort(),[...items].sort());const sim=createState(run.loadout);assert.equal(sim.damage,items.includes('carbine')?2:1);assert.equal(sim.ammo,items.includes('ammo-pouch')?36:12);assert.equal(sim.vest,items.includes('vest')?2:0);}}
  const restored=new QuestSession(context);await restored.ready;assert.deepEqual(restored.state.teams[t.id].inventory,t.inventory);assert.equal(restored.report().attempts.length,r.report().attempts.length);
 }
});
test('fraction policy covers value, raw form, signs, integer entry and explicit denominator exceptions',()=>{
 for(const [answerType,answer,input,correct,reason]of [['fraction','1/2','1/2',true],['fraction','1/2','2/4',false,'equivalent-unsimplified'],['fraction','-3/4','-6/8',false,'equivalent-unsimplified'],['mixed','2 1/2','2 2/4',false,'equivalent-unsimplified'],['mixed','-2 1/3','-2 2/6',false,'equivalent-unsimplified'],['fraction','7/3','7/3',true],['fraction','7/3','14/6',false,'equivalent-unsimplified'],['fraction','2/1','6/3',false,'equivalent-unsimplified'],['fraction','2/1','2',true],['fraction','0/1','0/5',false,'equivalent-unsimplified'],['fraction','0/1','0',true],['fraction','0/1','0/1',true],['fraction','-3/4',' 3 / -4 ',true],['decimal','.5','0.5',true]]){const r=checkItem({answerType,answer},input);assert.equal(r.correct,correct,input);if(reason)assert.equal(r.reason,reason);}
 for(const input of ['1/0','1/','.5','- / 4'])assert.equal(checkItem({answerType:'fraction',answer:'1/2'},input).valid,false);
 assert.notEqual(checkItem({answerType:'fraction',answer:'1/2'},'2/5').reason,'equivalent-unsimplified');
 assert.throws(()=>normalizeCustomItem({prompt:'Half',answerType:'fraction',answer:'2/4'}),/reduced/);
 assert.throws(()=>normalizeCustomItem({prompt:'Half',answerType:'fraction',answer:'1/2',acceptedAnswers:['2/4']}),/reduced/);
 const q=normalizeCustomItem({prompt:'Write one-half with denominator 8.',answerType:'fraction',answer:'4/8',fractionPolicy:'specified-denominator',requiredDenominator:8,representationInstruction:'Use denominator 8.'});assert.equal(checkItem(q,'4/8').correct,true);assert.equal(checkItem(q,'1/2').correct,false);
});
test('every preset module and difficulty uses the shared final-fraction contract',()=>{let fractions=0;for(const m of PRESET_MODULES)for(const band of ['beginner','intermediate','advanced'])for(let seed=0;seed<30;seed++){const q=generatePresetItem(m.id,seed,band);assert.equal(checkItem(q,q.answer).correct,true,JSON.stringify(q));if(q.answerType==='fraction'){fractions++;const [n,d]=q.answer.split('/').map(Number);assert.equal(checkItem(q,`${n*2}/${d*2}`).correct,false);}}assert.ok(fractions>100);});
test('unsimplified submission is recorded raw, cannot complete a gate, and correction is not first-attempt success',async()=>{const {r,t}=await setup();const m=r.members(t.id)[0];m.currentItem={id:'fraction-audit',moduleId:'fraction.simplify',moduleTitle:'Audit',prompt:'Give one-half.',answerType:'fraction',answer:'1/2',attempts:0};const result=await cmd(r,'math.submit',{deviceId:m.id,answer:'2/4'});assert.match(result.feedback.message,/value is correct/);assert.equal(m.itemsCompleted,0);assert.equal(r.state.attempts.at(-1).submitted,'2/4');assert.equal(r.state.attempts.at(-1).correct,false);await cmd(r,'math.submit',{deviceId:m.id,answer:'1/2'});assert.equal(m.firstAttemptCorrect,0);assert.equal(m.itemsCompleted,1);});
test('shared deadline closes late and never-started runs while preserving completed results and answers',async()=>{const {r,t}=await setup('vault-7',3);beginExtraction(r,t);const e=t.extraction;assert.equal(e.deadlineAt-e.stageEnteredAt,RULES.teamWindow);assert.equal(RULES.limit,180000);Object.assign(e.resultsByStudentId.s0,{status:'terminal',outcome:'extracted',activeElapsedMs:20000});Object.assign(e.resultsByStudentId.s1,{status:'active',activeElapsedMs:1000,startedAt:new Date().toISOString()});const attempts=structuredClone(r.state.attempts);settleExtractions(r,e.deadlineAt+1);assert.equal(t.stage,'victory');assert.equal(e.resultsByStudentId.s0.outcome,'extracted');assert.equal(e.resultsByStudentId.s1.outcome,'advanced');assert.equal(e.resultsByStudentId.s2.outcome,'advanced');assert.equal(e.completionReason,'shared-window-closed');assert.deepEqual(r.state.attempts,attempts);});
test('alarm interrupts every attack state for its full interval, including distant and newly added mobs',()=>{for(const phase of ['chase','windup','lunge']){const s=createState();s.x=1300;s.y=1200;const e={...s.enemies[0],x:1301,y:1201,phase,timer:.2};s.enemies=[e];triggerDistraction(s,'alarm');const until=s.distractions.alarm.until;step(s,{});assert.equal(s.health,3);assert.equal(e.phase,'alarm');s.enemies.push({...e,id:'new',x:2000,y:1160});s.time=until-.1;step(s,{fire:true});assert.ok(s.enemies.every(e=>e.phase==='alarm'));assert.equal(triggerDistraction(s,'alarm'),false);s.time=until;step(s,{});assert.equal(activeAlarm(s),null);assert.ok(s.enemies.every(e=>e.phase!=='alarm'));}});
test('alarm activates on car contact and bullets from both sides but not a near miss',()=>{for(const side of [-1,1]){const s=createState();s.enemies=[];const p=propBounds(PROPS.find(p=>p.id==='wreck1'));s.y=p.y+p.h/2;s.x=side<0?p.x-50:p.x+p.w+50;s.angle=side<0?0:Math.PI;step(s,{fire:true});for(let i=0;i<15;i++)step(s,{});assert.ok(activeAlarm(s));}const s=createState();s.enemies=[];const p=propBounds(PROPS[0]);s.x=p.x-11;s.y=p.y+p.h/2;step(s,{});assert.equal(activeAlarm(s),null);s.x=p.x-10;step(s,{});assert.ok(activeAlarm(s));});
test('store group survives every threat budget, door stays solid, both windows become passages',()=>{for(let threat=0;threat<5;threat++){const s=createState([], 'clinic',threat);assert.equal(s.enemies.filter(e=>e.storeGuard).length,8);assert.equal(toggleDoor(s,'store'),false);assert.equal(solid(s,1640,504),true);const windows=WINDOWS.filter(w=>w.room==='store');assert.equal(windows.length,2);for(const w of windows){breakWindow(s,w.id);assert.equal(solid(s,w.x+8,w.y+40),false);}triggerDistraction(s,'alarm');step(s,{});assert.ok(s.enemies.filter(e=>e.storeGuard).every(e=>e.phase==='alarm'));}});
test('shotgun eight-shell reward ignores carbine and pouch; switching/recovery never refill',()=>{const s=createState(['carbine','ammo-pouch']);s.enemies=[];collectShotgun(s);assert.equal(s.shells,8);step(s,{fire:true});assert.equal(s.shells,7);assert.equal(s.ammo,36);assert.equal(s.bullets.length,7);assert.ok(Math.abs(s.bullets.at(-1).angle-s.bullets[0].angle-SHOTGUN.spread)<1e-9);assert.ok(s.bullets.every(b=>b.damage===1));step(s,{weapon:true});assert.equal(s.weapon,'primary');step(s,{});step(s,{weapon:true});assert.equal(s.shells,7);assert.equal(collectShotgun(s),false);const r=restoreState(s,s.loadout);assert.equal(r.shells,7);assert.equal(r.weapon,'shotgun');});
test('garage ingress overrides alarm until entry; dead horde members stay dead after restoration',()=>{const s=createState();s.enemies=[];s.x=2208;s.y=752;completeTask(s,'fuse');completeTask(s,'power');triggerDistraction(s,'alarm');completeTask(s,'battery');step(s,{});assert.ok(s.enemies.every(e=>e.phase==='garage-ingress'));for(let i=0;i<180;i++)step(s,{});assert.ok(s.enemies.some(e=>e.ingressed&&e.phase==='alarm'));s.enemies[0].hp=0;const r=restoreState(s);assert.equal(r.enemies.find(e=>e.id===s.enemies[0].id).hp,0);assert.equal(r.enemies.filter(e=>e.horde).length,8);});
