import fs from 'node:fs';
// Move the shared host behind the game registry; keep the old import as a shim.
let host=fs.readFileSync('public/finale-host.js','utf8');
host=host.replace("import {nightfallAdapter} from './games/nightfall/adapter.js';\n",'').replace("import {GameAudio} from './engine/game-audio.js';","import {GameAudio} from './game-audio.js';").replace("import {NIGHTFALL} from './cartridges.js';",'');
host=host.replace('export class FinaleHost','export class GameHost').replace('constructor(root,{run,route,deadline,send,practice=false,paused=false})','constructor(root,{adapter,items=[],run,route,deadline,send,practice=false,paused=false})').replace('this.adapter=nightfallAdapter;','this.adapter=adapter;this.items=items;').replace('NIGHTFALL.items.find','this.items.find');
host=host.replace('if(paused&&!this.paused)this.clear();','if(paused!==this.paused){this.clear();this.gameAudio.pause(paused||this.localPaused);}');
fs.writeFileSync('public/engine/game-host.js',host);
fs.writeFileSync('public/finale-host.js',`// Backward-compatible import; new callers should use the game registry.\nimport {GameHost} from './engine/game-host.js';\nimport {gameFor} from './games/registry.js';\nimport {NIGHTFALL} from './cartridges.js';\nexport class FinaleHost extends GameHost{constructor(root,options){super(root,{...options,adapter:gameFor(NIGHTFALL.gameId),items:NIGHTFALL.items});}}\n`);
let app=fs.readFileSync('public/app.js','utf8').replace('90-second top-down finale','city survival finale · manual aiming');app=app.replace("${setupCartridge==='nightfall'?", "${developerTools()}${setupCartridge==='nightfall'?");fs.writeFileSync('public/app.js',app);
fs.mkdirSync('src/cartridges/nightfall',{recursive:true});let exp=fs.readFileSync('src/expansion.js','utf8').replace("'../public/cartridges.js'","'../../../public/cartridges.js'");fs.writeFileSync('src/cartridges/nightfall/server.js',exp);fs.writeFileSync('src/expansion.js',"// Compatibility export for the original M1 entry point.\nexport * from './cartridges/nightfall/server.js';\n");
let audio=fs.readFileSync('public/engine/game-audio.js','utf8').replace("'enemy-death':4,hurt:5","'enemy-death':4,death:4,hurt:5");fs.writeFileSync('public/engine/game-audio.js',audio);
let css=fs.readFileSync('public/nightfall.css','utf8');css+='\n.nf-controls{flex-wrap:wrap;gap:8px}.nf-controls button{font-size:14px;font-weight:700}.nf-overlay button:disabled{opacity:.5}.nf-screen{border:1px solid #657575}.nf-hud{line-height:1.7}.nf-game{box-shadow:0 12px 35px #07131c44}\n';fs.writeFileSync('public/nightfall.css',css);
