import fs from 'node:fs';
for(const p of ['Deploy_Backend_Windows.bat','package-lock.json']){let s=fs.readFileSync(p,'utf8').replaceAll('0.7.0','0.9.1');fs.writeFileSync(p,s);}
let s=fs.readFileSync('public/cartridges.js','utf8');
s=s.replace('At the end, each of you crosses the street alone to recover an override key and reach the bus. You do not have to clear the city. You only have to get through it.','At the end, each of you plays an individual evacuation run: search Maintenance and Dispatch, restore the substation, open the garage, and bring a replacement battery back to the bus. You do not have to clear the city. You have to keep moving.');
s=s.replace('The ignition catches. For the first time tonight, the departure board might be telling the truth. Sol opens the terminal supply cage.','The crew has mapped a repair route, but the bus is still dark. Sol opens the terminal supply cage.');
s=s.replace('The crew has solved the immediate problem. Now it must choose what kind of escape this will be.','The crew has a repair plan. Before anyone steps into the street, it must choose what kind of escape this will be.');
s=s.replace('The replacement battery is connected. Sol asks everyone to step back, then turns the key. The engine fires with a sound so ordinary that, for a second, the terminal feels like a terminal again.','The garage inventory confirms a charged replacement battery. But the electric shutter is locked down, and the terminal key hooks are empty. Sol spreads the district map across the dashboard. The escape now has a plan, not yet a working engine.');
s=s.replace('One problem remains: the street-side barrier needs an override key from the security booth. Finish the departure checks and claim forty supply credits. After choosing equipment and a destination, each crew member must cross the last dangerous stretch to the bus.','Finish the departure checks and claim forty supply credits. Then choose equipment and a destination. Each crew member will run a solo evacuation simulation: restore power, recover the keys and battery, and get the bus moving.');
fs.writeFileSync('public/cartridges.js',s);
let meta=JSON.parse(fs.readFileSync('VERSION.json'));meta.prototype='Live teacher controls and expanded Nightfall city mission';meta.proposedGithubPagesUrl='https://williammcada.github.io/MathQuest/';fs.writeFileSync('VERSION.json',JSON.stringify(meta,null,2)+'\n');
let renderer=fs.readFileSync('public/games/nightfall/renderer.js','utf8').replace('frame=e.hp<=0?7:',"frame=e.hp<=0?(s.time-(e.deathTime??-10)<.18?6:7):");fs.writeFileSync('public/games/nightfall/renderer.js',renderer);
let sim=fs.readFileSync('public/games/nightfall/simulation.js','utf8').replace('if(running){s.noise=',"if((dx||dy)&&s.time-(s.lastStep||0)>(running?.28:.48)){s.lastStep=s.time;emit(s,'step','');}\n if(running){s.noise=");fs.writeFileSync('public/games/nightfall/simulation.js',sim);
