import fs from 'node:fs';
const p='public/finale-host.js';let s=fs.readFileSync(p,'utf8');
s=s.replace("import {newRun,step,restoreRun,WALLS,WORLD,pickups} from './nightfall-core.js';", "import {nightfallAdapter} from './games/nightfall/adapter.js';\nimport {GameAudio} from './engine/game-audio.js';");
s=s.replace("this.root=root;", "this.adapter=nightfallAdapter;this.art=null;this.gameAudio=new GameAudio(this.adapter.media);this.root=root;");
s=s.replace('this.input={};','this.input={tank:true};');
s=s.replace('this.s=restoreRun(saved?.seq>=run.seq?saved.snapshot:run.snapshot,run.loadout||[],route);','this.s=this.adapter.create({...run,route,snapshot:saved?.seq>=run.seq?saved.snapshot:run.snapshot});');
s=s.replace('this.render();this.last=',"this.render();this.adapter.loadArt().then(art=>{if(!this.dead){this.art=art;this.showOverlay();}}).catch(e=>{if(!this.dead){this.status.textContent='Artwork unavailable. Use the assisted route.';this.artError=e.message;this.showOverlay();}});this.last=");
s=s.replace('Standard kit: 36 rounds, 3 health','Standard kit: 12 rounds, 3 health');
s=s.replace('Nightfall street crossing: collect the key, then reach the bus','Search the city, restore power, and repair the evacuation bus');
s=s.replace('<button class="nf-fire" data-key="fire">FIRE</button>','<button data-key="run">RUN</button><button class="nf-fire" data-key="fire">FIRE</button><button data-key="interact">SEARCH / USE (hold)</button><button data-map>MAP</button>');
s=s.replace("['up','down','left','right','fire']","['up','down','left','right','fire','run','interact']");
s=s.replace("' ':'fire'}","' ':'fire',Shift:'run',e:'interact'}");
s=s.replace("on(this.root.querySelector('[data-reset]')", "on(this.root.querySelector('[data-map]'),'click',()=>this.s.map=!this.s.map);\n    on(this.root.querySelector('[data-reset]')");
function method(name,next,body){const a=s.indexOf('  '+name+'('),b=s.indexOf('  '+next+'(',a);if(a<0||b<0)throw Error(name);s=s.slice(0,a)+body+'\n'+s.slice(b);}
method('assisted','update',`  assisted(){this.adapter.assisted(this.s,this.overlay,()=>{this.persist();if(this.s.outcome)this.finish();else this.assisted();});}`);
method('beep','draw',`  beep(event){this.gameAudio.effect(event.type||event);}`);
method('draw','destroy',`  draw(){if(this.ctx&&this.art)this.adapter.render(this.ctx,this.s,this.art);this.hud.textContent=this.adapter.hud(this.s)+' | '+this.adapter.objective(this.s)+' | '+(this.s.message||'');}`);
s=s.replace("this.audio ||= new (window.AudioContext||window.webkitAudioContext)();await this.audio.resume();this.sound=!this.sound;", "await this.gameAudio.toggle();this.sound=this.gameAudio.enabled;");
s=s.replace('this.starting=true;','this.starting=true;this.gameAudio.start().catch(()=>{this.status.textContent="Audio unavailable.";});');
s=s.replace('this.s=restoreRun(value,this.run.loadout,this.s.route);','this.s=this.adapter.create({...this.run,snapshot:value,route:this.s.route});');
s=s.replace("this.overlay.innerHTML='<h2>One last crossing</h2><p>Collect the gold key in the north-east. Then reach the green bus in the south-east. Fire auto-aims at the nearest visible target. You can avoid enemies; no kills are required.</p><p>Move: arrows / WASD. Fire: Space. Touch controls are below.</p><button data-start>Start 90-second crossing</button>';", "this.overlay.innerHTML=`<h2>Last Bus Out</h2><p>${this.adapter.instructions}</p><p>${this.adapter.controls}</p><button data-start ${this.mode==='action'&&!this.art?'disabled':''}>${this.art||this.mode==='assisted'?'Start mission':'Loading artwork…'}</button>`;");
s=s.replace('The team window still applies to a personal pause.','Use Pause again to resume.');
s=s.replace('Math.min(90000,Math.round(this.s.time*1000))','Math.round(this.s.time*1000)');
s=s.replace('step(this.s,this.input);','this.adapter.step(this.s,{...this.input,tank:true},1/60);');
s=s.replace('else this.s.time=Math.min(90,this.s.time+dt);','else this.s.time+=dt;');
s=s.replace("if(this.s.time>=90&&!this.s.outcome)this.s.outcome='timed_out';", "this.gameAudio.music(this.s.outcome?'ending':this.s.enemies.some(e=>e.hp>0&&Math.hypot(e.x-this.s.x,e.y-this.s.y)<180)?'danger':'ambient');");
s=s.replace('this.audio?.close();','this.gameAudio.destroy();');
s=s.replace('this.input={};this.keys','this.input={tank:true};this.keys');
s=s.replace('this.localPaused=!this.localPaused;this.clear();','this.localPaused=!this.localPaused;this.gameAudio.pause(this.localPaused||this.paused);this.clear();');
s=s.replace("on(window,'blur',()=>{this.clear();this.persist();});", "on(window,'blur',()=>{this.clear();this.localPaused=true;this.gameAudio.pause(true);this.persist();this.showOverlay();});");
fs.writeFileSync(p,s);
